package com.chinasofti.dao;

import com.chinasofti.ssm.model.Score;

public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    int deleteByPrimaryKey(Integer studentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    int insertSelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    Score selectByPrimaryKey(Integer studentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    int updateByPrimaryKeySelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    int updateByPrimaryKey(Score record);
}