package com.chinasofti.ssm.model;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classname
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    private String classname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classid
     *
     * @return the value of class.classid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classid
     *
     * @param classid the value for class.classid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classname
     *
     * @return the value of class.classname
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classname
     *
     * @param classname the value for class.classname
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((classid == null) ? 0 : classid.hashCode());
		result = prime * result + ((classname == null) ? 0 : classname.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Class other = (Class) obj;
		if (classid == null) {
			if (other.classid != null)
				return false;
		} else if (!classid.equals(other.classid))
			return false;
		if (classname == null) {
			if (other.classname != null)
				return false;
		} else if (!classname.equals(other.classname))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Class [classid=" + classid + ", classname=" + classname + "]";
	}

	public Class(Integer classid, String classname) {
		this.classid = classid;
		this.classname = classname;
	}

	public Class() {
	}
}