package com.chinasofti.ssm.model;

public class Score {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.studentid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    private Integer studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.classid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.studentname
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    private String studentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.score
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.studentid
     *
     * @return the value of score.studentid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.studentid
     *
     * @param studentid the value for score.studentid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.classid
     *
     * @return the value of score.classid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.classid
     *
     * @param classid the value for score.classid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.studentname
     *
     * @return the value of score.studentname
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public String getStudentname() {
        return studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.studentname
     *
     * @param studentname the value for score.studentname
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public void setStudentname(String studentname) {
        this.studentname = studentname == null ? null : studentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.score
     *
     * @return the value of score.score
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.score
     *
     * @param score the value for score.score
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((classid == null) ? 0 : classid.hashCode());
		result = prime * result + ((score == null) ? 0 : score.hashCode());
		result = prime * result + ((studentid == null) ? 0 : studentid.hashCode());
		result = prime * result + ((studentname == null) ? 0 : studentname.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Score other = (Score) obj;
		if (classid == null) {
			if (other.classid != null)
				return false;
		} else if (!classid.equals(other.classid))
			return false;
		if (score == null) {
			if (other.score != null)
				return false;
		} else if (!score.equals(other.score))
			return false;
		if (studentid == null) {
			if (other.studentid != null)
				return false;
		} else if (!studentid.equals(other.studentid))
			return false;
		if (studentname == null) {
			if (other.studentname != null)
				return false;
		} else if (!studentname.equals(other.studentname))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Score [studentid=" + studentid + ", classid=" + classid + ", studentname=" + studentname + ", score="
				+ score + "]";
	}

	public Score(Integer studentid, Integer classid, String studentname, Integer score) {
		this.studentid = studentid;
		this.classid = classid;
		this.studentname = studentname;
		this.score = score;
	}

	public Score() {
	}
    
}