package com.chinasofti.ssm.model;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.userid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.username
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.classid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    private Integer classid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.userid
     *
     * @return the value of student.userid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public Long  getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.userid
     *
     * @param userid the value for student.userid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.username
     *
     * @return the value of student.username
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.username
     *
     * @param username the value for student.username
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.classid
     *
     * @return the value of student.classid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.classid
     *
     * @param classid the value for student.classid
     *
     * @mbggenerated Thu Jul 13 16:27:23 CST 2017
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((classid == null) ? 0 : classid.hashCode());
		result = prime * result + ((password == null) ? 0 : password.hashCode());
		result = prime * result + ((userid == null) ? 0 : userid.hashCode());
		result = prime * result + ((username == null) ? 0 : username.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Student other = (Student) obj;
		if (classid == null) {
			if (other.classid != null)
				return false;
		} else if (!classid.equals(other.classid))
			return false;
		if (password == null) {
			if (other.password != null)
				return false;
		} else if (!password.equals(other.password))
			return false;
		if (userid == null) {
			if (other.userid != null)
				return false;
		} else if (!userid.equals(other.userid))
			return false;
		if (username == null) {
			if (other.username != null)
				return false;
		} else if (!username.equals(other.username))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Student [userid=" + userid + ", username=" + username + ", password=" + password + ", classid="
				+ classid + "]";
	}

	public Student(Long userid, String username, String password, Integer classid) {
		this.userid = userid;
		this.username = username;
		this.password = password;
		this.classid = classid;
	}

	public Student() {
	}
    
}